[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# better deterministic deploys
bytecode_hash = "none"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "create2-helpers/=lib/create2-helpers/src/",
    "a16z-halmos-cheatcodes/=lib/halmos-cheatcodes/src/",
    "deterministic-proxy-factory/=lib/deterministic-proxy-factory/src/",
]
optimizer_runs = 9999999
solc_version = "0.8.30"
fs_permissions = [
    { access = "read", path = "out" },
    { access = "read", path = "forge-utils" },
]
dynamic_test_linking = true

[profile.gambit]
via_ir = false
optimizer = false
dynamic_test_linking = false

[profile.gambit.invariant]
runs = 0

[profile.halmos]
dynamic_test_linking = false

[bind_json]
out = "forge-utils/JsonBindings.sol"

[fmt]
line_length = 100
single_line_statement_blocks = "multi"
sort_imports = true
contract_new_lines = true
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
multline_func_header = "all"

[lint]
exclude_lints = ["mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
